export const POPULAR_LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Chinese (Mandarin)',
  'Japanese',
  'Korean',
  'Arabic',
  'Russian',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Danish',
  'Hindi',
  'Turkish',
  'Polish',
  'Greek',
  'Hebrew',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malay',
  'Finnish',
  'Czech',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Slovak',
  'Slovenian',
  'Estonian',
  'Latvian',
  'Lithuanian',
  'Ukrainian',
  'Bengali',
  'Urdu',
  'Persian',
  'Swahili',
] as const;

export const DEFAULT_ORIGINAL_LANGUAGE = 'Vietnamese';
export const DEFAULT_TARGET_LANGUAGE = 'English';

export type Language = typeof POPULAR_LANGUAGES[number];
